# Generated by Django 3.2.9 on 2021-11-07 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max 150 символов', max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(help_text='max 150 символов', max_length=150, verbose_name='Слаг')),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='Max 32767', verbose_name='Порядок (чем меньше, тем выше).')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('weight', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('slug',),
                'default_related_name': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max 150 символов', max_length=150, verbose_name='Название')),
                ('text', models.TextField(help_text='Напишите, насколько оно классное', verbose_name='Описание')),
                ('category', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(related_name='items', to='catalog.Tag')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'default_related_name': 'items',
            },
        ),
    ]
